BACKEND: tensorrt
SCHEDULE:
  FUSE_BN: True
  BN_TUNING: True
W:
  QSCHEME: per-channel-symmetric
  QUANTIZER:
    TYPE: uniform
    BIT: 8
  OBSERVER:
    TYPE: MINMAX
A:
  QSCHEME: per-tensor-symmetric
  QUANTIZER:
    TYPE: uniform
    BIT: 8
  OBSERVER:
    TYPE: MINMAX
    LAYOUT: NCHW
